### PR TITLE
[core] add possibility to bypass Tag tracking using cookie

### PR DESCRIPTION
**Pull request by WnP**

### CODE REVIEW

**Comment by Lacrymology** [comment]
@WnP, @chaahk would either of you explain what this does and why?

**Comment by WnP** [comment]
Hi @Lacrymology,

Oops, sorry, I forgot about the description.

## Use case

in some country -like mine- users should be able to disable tracking like Google Tag Manager do.

## Solution

with this PR we can set a custom cookie, which when present disable tracking by making this tag returning nothing.

As you can see in the diff this cookie is named `GOOGLE_TAG_BYPASS_COOKIE`, which I guess is a quite explicite name, let me know your through.

Indeed this cookie should be set using javascript or whatever else.

That's all, hope you'll like it.

**Comment by WnP** [comment]
Hi @Lacrymology

Any chance to have a released version with this feature?

Thanks

**Comment by Lacrymology** [comment]
@WnP sorry, I missed your message. I'll release it in a while (few hours)

**Comment by Lacrymology** [comment]
released

**Pull request merged**
